# Generated by Django 3.2.9 on 2021-11-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211125_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
